spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_sample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 10113-Xavi

  jpa:
    hibernate:
      ddl-auto: none
